### PR TITLE
Implement a CLI-editable config file (#116)

### PR DESCRIPTION
**Pull request by emk**
For now, this allows you to specify permanent `--temporary`
arguments:

    dbcrossbar config add temporary s3://example/temp/
    dbcrossbar config rm temporary s3://example/temp/

This file lives in `$DBCROSSBAR_CONFIG_DIR/dbcrossbar.toml`,
and `$DBCROSSBAR_CONFIG_DIR` defaults to a platform-appropriate
location.

The actual config-editing code uses `toml_edit`, which allows
us to programmatically edit a TOML file without losing existing
comments and whitespace. Unfortunately, this requires some
fairly verbose code, because it's not as convenient as `serde`.

I've deliberately kept the configuration `Key` type opaque,
because I plan to support driver- and host-specific config keys,
and I don't want to break the library API when I add them.

This doesn't implement all of #116, but it's probably most of what we need for v0.4.0-beta.1.

### CODE REVIEW

**Comment by seamusabshere** [comment]
why toml? there's no stdlib parser for that in most languages... what if i need to programmatically generate it?

can you keep it json, then you get to keep serde?

**Comment by emk** [comment]
TOML is pretty much the config-file standard in the Rust ecosystem, because it's well-suited to config files with comments, whitespace and trailing commas, and it doesn't require pulling a parser for the 200-page YAML specification.

In this particular case, you shouldn't be generating config files programmatically. Either use `dbcrossbar config` to edit them, build then by hand, or just use CLI arguments.

**Comment by seamusabshere** [comment]
so options are:

1. you support json in addition to toml (i wasn't suggesting yaml)
2. our code repeatedly shells out to `dbcrossbar config` to set auth settings in one-use containers
3. our code writes toml from scratch
4. i create a toml template with placeholders and our code replaces the placeholders at runtime

**Comment by emk** [comment]
We discussed this offline, and cleared up a point of confusion: Credentials will never be stored in `dbcrossbar.toml`, and very few programmatic callers of `dbcrossbar` would ever need to change `dbcrossbar.toml`, because all the options are also available on the command line.

**Pull request merged**
